#
# Module manifest for module 'Bca.Nuget'
#
# Generated by: BCabrera
#
# Generated on: 2019-02-11
#

@{

    # Script module or binary module file associated with this manifest.
    RootModule      = 'Bca.Nuget'

    # Version number of this module.
    ModuleVersion   = '0.0.7'

    # Supported PSEditions
    # CompatiblePSEditions = @()

    # ID used to uniquely identify this module
    GUID            = 'f2f8ed24-7db8-4ba6-8888-c809cb3bcdad'

    # Author of this module
    Author          = 'Baptiste Cabrera'

    # Company or vendor of this module
    CompanyName     = 'Bca'

    # Copyright statement for this module
    Copyright       = '(c) 2020 Bca. All rights reserved.'

    # Description of the functionality provided by this module
    Description     = 'PowerShell module to create and manage NuGet packages.'

    # Minimum version of the Windows PowerShell engine required by this module
    # PowerShellVersion = ''

    # Name of the Windows PowerShell host required by this module
    # PowerShellHostName = ''

    # Minimum version of the Windows PowerShell host required by this module
    # PowerShellHostVersion = ''

    # Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
    # DotNetFrameworkVersion = ''

    # Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
    # CLRVersion = ''

    # Processor architecture (None, X86, Amd64) required by this module
    # ProcessorArchitecture = ''

    # Modules that must be imported into the global environment prior to importing this module
    RequiredModules = @(@{ ModuleName = "Bca.Spdx" ; ModuleVersion = "0.0.8" })

    # Assemblies that must be loaded prior to importing this module
    # RequiredAssemblies = @()

    # Script files (.ps1) that are run in the caller's environment prior to importing this module.
    # ScriptsToProcess = @()

    # Type files (.ps1xml) to be loaded when importing this module
    # TypesToProcess = @()

    # Format files (.ps1xml) to be loaded when importing this module
    # FormatsToProcess = @()

    # Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
    # NestedModules = @()

    # Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
    # FunctionsToExport = @()

    # Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
    # CmdletsToExport = @()

    # Variables to export from this module
    # VariablesToExport = '*'

    # Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
    # AliasesToExport = @()

    # DSC resources to export from this module
    # DscResourcesToExport = @()

    # List of all modules packaged with this module
    # ModuleList = @()

    # List of all files packaged with this module
    # FileList = @()

    # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
    PrivateData     = @{

        PSData = @{

            # Tags applied to this module. These help with module discovery in online galleries.
            Tags       = @('Package', 'Packaging', 'PackageManager', 'NuGet')

            # A URL to the license for this module.
            # LicenseUri = ''

            # A URL to the main website for this project.
            ProjectUri   = 'https://github.com/bapcabrera/bca-nuget'

            # A URL to an icon representing this module.
            IconUri    = ''

            # ReleaseNotes of this module
            ReleaseNotes = '0.0.7:
- Install-NuGet: New function that will install NuGet if not present when importing the module (can be used to update with Force switch).
- Update-NuGet: New function that will update NuGet to the latest version.

0.0.6:
- ConvertTo-NuspecManifest: Added support for PowerShell Script Info objects.

0.0.5:
- Bug fixes.

0.0.4:
- ConvertTo-NuspecManifest: Added support for Module objects.

0.0.3:
- Added files support (Add-NuspecContentFile and Add-NuspecFile);
- Set-NuspecLicense: New function that supports either SPDX license or file;
- Added a dependency on module Bca.Spdx.

0.0.2:
- Added new function for Nuspec properties (Get-NuspecProperty, Set-NuspecProperty, Resolve-NuspecProperty);
- ConvertTo-NuspecManifest: Moved a great deal of logic in Resolve-NuspecProperty.

0.0.1:
- First version.'

            # Prerelease of this module
            Prerelease = ""
        } # End of PSData hashtable

    } # End of PrivateData hashtable

    # HelpInfo URI of this module
    # HelpInfoURI = ''

    # Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
    # DefaultCommandPrefix = ''

}

